 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/activities", type: :request do
  
  # Activity. As you add validations to Activity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Activity.create! valid_attributes
      get activities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      activity = Activity.create! valid_attributes
      get activity_url(activity)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_activity_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      activity = Activity.create! valid_attributes
      get edit_activity_url(activity)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Activity" do
        expect {
          post activities_url, params: { activity: valid_attributes }
        }.to change(Activity, :count).by(1)
      end

      it "redirects to the created activity" do
        post activities_url, params: { activity: valid_attributes }
        expect(response).to redirect_to(activity_url(Activity.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Activity" do
        expect {
          post activities_url, params: { activity: invalid_attributes }
        }.to change(Activity, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post activities_url, params: { activity: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested activity" do
        activity = Activity.create! valid_attributes
        patch activity_url(activity), params: { activity: new_attributes }
        activity.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the activity" do
        activity = Activity.create! valid_attributes
        patch activity_url(activity), params: { activity: new_attributes }
        activity.reload
        expect(response).to redirect_to(activity_url(activity))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        activity = Activity.create! valid_attributes
        patch activity_url(activity), params: { activity: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested activity" do
      activity = Activity.create! valid_attributes
      expect {
        delete activity_url(activity)
      }.to change(Activity, :count).by(-1)
    end

    it "redirects to the activities list" do
      activity = Activity.create! valid_attributes
      delete activity_url(activity)
      expect(response).to redirect_to(activities_url)
    end
  end
end
